name: build
on: 
  push:
    branches:
      -dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: copier code depuis github vers notre sereveur ubuntu
      uses: actions/checkout@v3
    - name: installer node js
      uses: actions/setup-node@v3
    - name: installation des packages JS
      run: npm install
    - name: Build lapp JS
      run: npm run build
