name: build
on: 
  push:
    branches:
      -dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: copier code depuis github vers notre sereveur ubuntu
      uses: actions/checkout@v3
